######################
## Configuration file for RNAseq and DEseq pipelines
## Used in ErcanLab_RNA-seq_analysis_v2.docx and ErcanLab_DE-seq_analysis_v1.docx protocols
## found in Ercan's lab google drive.
##
## Author: Diogo Mesquita - dam740@nyu.edu
##
## Usage:
##   Edit this configuration with the values for your analysis.
##   The only fields that you probably do NOT need to change are 'c_elegans_wbid_to_gene',
##   'c_elegans_annots' and 'sbatch_scripts'.
##
##   All replicates should be added to the 'infiles' list as a separate element.
##
##   Elements of 'infiles' must have:
##       - id:        unique identifier of biological replicate. Technical replicates
##                    must have the same id
##       - condition: condition name. These are generic, all replicates from
##                    the same condition should have the same "condition"
##       - type:      must only take one of two values: "control" or "treatment"
##       - fastq:     fastq file name (can be or not gzipped; do NOT include path to file)
##
##
---
# title of the experiment - make sure the same name doesn't exit in /scratch/cgsb/ercan/rna/deseq 
experiment_title: vc100_emb

nyuid: dam740
mail: dam740@nyu.edu

# C. elegans annotations
c_elegans_wbid_to_gene: /scratch/cgsb/ercan/annot/c_elegans.WS220.annotations.WBID_to_gene.txt
c_elegans_annots: /scratch/cgsb/ercan/annot/WS220_gene_annotations_WormMart_unique.xlsx

# scripts directory
sbatch_scripts: /scratch/cgsb/ercan/scripts/rna/slurm

infiles:
  - id: 1
    condition: N2
    type: control
    fastq: MK62_AGTCAA_L003_R1_001.fastq.gz

  - id: 1
    condition: N2
    type: control  
    fastq: MK74_AGTCAA_L006_R1_001.fastq.gz

  - id: 2
    condition: N2
    type: control
    fastq: MK63_AGTTCC_L003_R1_001.fastq.gz

  - id: 2
    condition: N2
    type: control
    fastq: MK75_AGTTCC_L006_R1_001.fastq.gz

  - id: 3
    condition: N2
    type: control
    fastq: MK41_AGTCAA_L004_R1_001.fastq.gz

  - id: 4
    condition: N2
    type: control
    fastq: SEA38_ATCACG_L003_R1_001.fastq.gz

  - id: 5
    condition: N2
    type: control
    fastq: MK42_AGTTCC_L004_R1_001.fastq.gz

  - id: 6
    condition: N2
    type: control
    fastq: SEA48_CGATGT_L003_R1_001.fastq.gz

  - id: 7
    condition: N2
    type: control
    fastq: SEA36_CTTGTA_L005_R1_001.fastq.gz

  - id: 8
    condition: N2
    type: control
    fastq: SEA61_GGCTAC_L002_R1_001.fastq.gz

  - id: 9
    condition: N2
    type: control
    fastq: SEA37_GGCTAC_L005_R1_001.fastq.gz

  - id: 10
    condition: vc100
    type: treatment
    fastq: SEA133_ACAGTG_L003_R1_001.fastq.gz

  - id: 11
    condition: vc100
    type: treatment
    fastq: SEA147_GATCAG_L007_R1_001.fastq.gz

  - id: 12
    condition: vc100
    type: treatment
    fastq: SEA148_AGTCAA_L007_R1_001.fastq.gz
